[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/background/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.next/server/pages/api/:splat"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 